### ISSUE TITLE
peerInterface deprecated: but is still a required field

### ISSUE THREAD

**Issue by ashwinnirantar** [appgate/terraform-provider-appgatesdp#321]
### Affected Resource(s)

* appgatesdp_appliance

https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/appliance

### Expected Behavior

peerInterface is a deprecated field, so can be removed from appgatesdp_appliance config 

### Actual Behavior

We are looking to remove this field from our config, however we received an error saying this field is required - as well as mentioned in the documentation that this is still required: https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/appliance 

<img width="234" alt="image" src="https://github.com/appgate/terraform-provider-appgatesdp/assets/83620145/123dfe53-e708-4cd7-bf01-29db5eddf87a">

### Steps to Reproduce

Remove peerInterface from `appgatesdp_appliance` 

### References

Issue referenced previously: https://github.com/appgate/terraform-provider-appgatesdp/issues/169

**Comment by danijeel** [comment]
Hi @ashwinnirantar ,

I see that we could expand and improve on this topic in the documentation.
It depends on the version of the appliance for your primary controller is using in your appgate sdp collective.

`peer_interface` used to be Required, but since 6.0 it has been changed to Optional.

We don't want to remove it yet [until we have dropped support for 5.5](https://www.appgate.com/support/software-defined-perimeter-support), which reached end of life on 31 December 2023.


For example, If I try to use `peer_interface` on 6.2 I will be presented by a error message
```sh

appgatesdp_appliance.test_error: Creating...
╷
│ Error: peer_interface is not supported in 6.2.0+estimated
│
│   with appgatesdp_appliance.test_error,
│   on main.tf line 15, in resource "appgatesdp_appliance" "test_error":
│   15: resource "appgatesdp_appliance" "test_error" {
│
│ peer_interface is removed in >= 6.0.
│ All connections will be handled by client_interface and admin_interface in the future.
│ The hostname field is used as identifier and will take over the hostname field in
│ the root of Appliance when this interface is removed


```

**Comment by ashwinnirantar** [comment]
@danijeel Thanks for your response, that makes more sense! We are on v6.1.x so I think we can skip the use of this field. I haven't tried deploying yet, but in theory we should no longer require it right?

**Comment by ashwinnirantar** [comment]
After running terraform plan on removing peer_interface for appliance version v6.1.x - I can confirm that peer_interface is an optional field. @danijeel We just need to update documentation to reflect that, but this is not an active issue and I am closing it! Thanks for your help on this
