### ISSUE TITLE
Adjust administrative_role privileges to TypeSet

### ISSUE THREAD

**Issue by stephengroat** [appgate/terraform-provider-appgatesdp#97]
Since `privliges` should be an unordered list, shouldn't it be a `TypeSet` instead of a `TypeList`?

https://github.com/appgate/terraform-provider-appgate-sdp/blob/23c06769b48cd75c3904aaffcb40216fdbdc1656/appgate/resource_appgate_administrative_role.go#L62

**Comment by danijeel** [comment]
Hey!

i don't think its possible to change `privileges` to `schema.TypeSet`, since `privileges`  contain computed values, so we cant compute a correct set hash for it.
I've not found a way for it atleast, if there are, PRs are welcome. For now i think this is a limitation within the terraform-plugin-sdk as Ive seen similiar issues in their repository. we have the same problem in #98
