### ISSUE TITLE
Adjust entitlement actions to TypeSet

### ISSUE THREAD

**Issue by stephengroat-dd** [appgate/terraform-provider-appgatesdp#98]
similar to #97, the entitlement actions are unordered, so shouldn't they be a `TypeSet` instead of a `TypeList`?

https://github.com/appgate/terraform-provider-appgate-sdp/blob/23c06769b48cd75c3904aaffcb40216fdbdc1656/appgate/resource_appgate_entitlement.go#L96

**Comment by danijeel** [comment]
Hey!

i don't think its possible to change `actions` to `schema.TypeSet`, since `actions`  contain computed values, so we cant compute a correct set hash for it. I've not found a way for it atleast, if there are, PRs are welcome. For now i think this is a limitation within the terraform-plugin-sdk as Ive seen similiar issues in their repository. we have the same problem in #97

**Comment by stephengroat** [comment]
> since `actions` contain computed values

what fields are the computed values? i only see `entitlement_id`, which isn't in the list

**Comment by danijeel** [comment]
`actions.monitor` is computed, in the schema we have specified it `DefaultFunc` (this should probably be replaced by compute instead), the API response will always include an monitor, even though it has not been specified in the tf files, so it acts as a compute value. we might be able to use [CustomDiff](https://www.terraform.io/docs/extend/resources/customizing-differences.html) to detect this, but its tricky since `actions` would be a nested structure.

**Comment by stephengroat** [comment]
in doing some quick testing, i think there's 2 options

1. what about making `actions.monitor` `Required` instead of `Optional`? that way, the API response would fit inside of the `actions.monitor` response, but the `DefaultFunc` would compute the defaults
2. (preferred method) the `monitor` elements of `enabled` and `timeout` could be moved outside of the `monitor` block and to the `actions` block, something like `monitor_enabled` and `monitor_timeout`. That way, these elements could have defaults that are easily populated. slight mods to the create/read logic, but nothing too bad

this issue is leading to nasty diffs since it's not really a list, it forcing large re-ordering when it shouldn't be

**Comment by danijeel** [comment]
>     2\. (preferred method) the `monitor` elements of `enabled` and `timeout` could be moved outside of the `monitor` block and to the `actions` block, something like `monitor_enabled` and `monitor_timeout`. That way, these elements could have defaults that are easily populated. slight mods to the create/read logic, but nothing too bad

this might work, I can test and see if I can do it while maintaining backwards compatibility for `monitor {}`

**Comment by danijeel** [comment]
I've updated the entitlment.actions from TypeList to TypeSet in master now, with the same schema as before for monitor, this was solved in #110
